FROM python:3.10.10-slim-bullseye

COPY ./requirements.txt ./requirements.txt

RUN apt-get update && apt-get upgrade -y && apt-get install -y build-essential
RUN pip install -r requirements.txt

COPY . .

CMD ["python", "main.py"]